### ISSUE TITLE
app_sample cannot read ds_sample

### ISSUE THREAD

**Issue by adamzchmbr** [twain/twain-samples#50]
hi.
im beginner of twain driver.
first of all, i downloaded this project and compiled successfully.
i used vs2015 and qt4.8.7 on windows10 x64.

i moved compiled TWAINDS_Sample32.ds to "c:\windows\twain_32\sample2\" and then that folder is contain FreeImage.dll, TWAIN_App_mfc.exe, TWAINDS_Sample32.ds, TWAINDSM.dll

but when execute TWAIN_App_mfc.exe, the list has nothing and two buttons are disabled.
am i miss something?

and where can i see some guides or what?
i hope you understand my question.

thank you.

**Comment by WaqarAzeem** [comment]
Following files are required in C:\Windows\twain_32\sample2

For Qt version 4

- FreeImage.dll
- QtCore4.dll
- QtGui4.dll
- TWAIN_logo.png
- TWAINDS_Sample32.ds

I'm using Visual Studio 2017 to compile the project with Qt 5 therefore in my **project properties** at **Linker > Input > Additional Dependencies** I have following

User32.lib;FreeImage.lib;qtmain.lib;Qt5Core.lib;**Qt5Widgets**.lib;Qt5Gui.lib;

And the respective Qt DLL files are located at C:\Qt\Qt5.12.3\5.12.3\msvc2017\bin
